Family table
greenbone/ospd-openvas pull request #366
Opened 2020-12-22 15:02 UTC by jjnicola

**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry

2020-12-28 09:49 UTC, cfi-gb requested changes

2020-12-28 09:49 UTC, cfi-gb commented on CHANGELOG.md
> +- Launch NVTs or notus driver, depending on availability. [#366](https://github.com/greenbone/ospd-openvas/pull/366)
```suggestion
- Launch VTs or Notus driver, depending on availability. [#366](https://github.com/greenbone/ospd-openvas/pull/366)
```

2021-01-04 07:46 UTC, ArnoStiefvater commented on ospd_openvas/notus/metadata.py
> +        csv file as dictionary:
```suggestion
        """Return the dictionary from the Notus metadata csv file which holds the driver script OID for the corresponding LSC family. This dictionary has one entry:
```

2021-01-04 08:12 UTC, ArnoStiefvater approved these changes

2021-01-04 08:12 UTC, merged