Prepare for release 21.04.0
greenbone/ospd-openvas pull request #402
Opened 2021-04-15 10:58 UTC by jjnicola

**What**:
Prepare for release 21.04.0

**Why**:

**How**:

**Checklist**:

- [ ] Tests
- [ ] [CHANGELOG](https://github.com/greenbone/gsa/blob/master/CHANGELOG.md) Entry

2021-04-15 15:03 UTC, timopollmeier requested changes
I think there are some small things that should be fixed here.

2021-04-15 15:03 UTC, timopollmeier commented on CHANGELOG.md
> +## [21.04.0] (unreleased)
Didn't we want to remove the padding zeroes in the version numbers, especially for Python projects?
Also, you forgot to add the date here.

2021-04-15 15:03 UTC, timopollmeier commented on CHANGELOG.md
> +## [20.08.2] (unreleases)
This should read "unreleased"
```suggestion
## [20.08.2] (unreleased)
```

2021-04-16 06:23 UTC, ArnoStiefvater approved these changes

2021-04-16 06:28 UTC, merged